# Form implementation generated from reading ui file 'dizajn.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1316, 777)
        Form.setStyleSheet("background-color: rgb(214, 214, 214);")

        self.frame_nmap = QtWidgets.QFrame(parent=Form)
        self.frame_nmap.setGeometry(QtCore.QRect(220, 10, 1081, 761))
        self.frame_nmap.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame_nmap.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_nmap.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_nmap.setObjectName("frame")
        self.frame_nmap.hide()

        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 10, 211, 561))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())

        #NMAP
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.Nmap)

        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)

        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_9.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)

        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_10.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)

        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_8.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)

        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Nmap"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.pushButton_9.setText(_translate("Form", "PushButton"))
        self.pushButton_10.setText(_translate("Form", "PushButton"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
        self.pushButton_7.setText(_translate("Form", "PushButton"))

    def Nmap(self):
        self.label_domain_name = QtWidgets.QLabel(parent=self.frame_nmap, text="Domain name")
        self.label_domain_name.setGeometry(QtCore.QRect(10,10, 150, 30))
        self.label_domain_name.setObjectName("label_domain_name")

        self.domain_name = QtWidgets.QLineEdit(parent=self.frame_nmap)
        self.domain_name.setGeometry(QtCore.QRect(100, 10, 200, 30))
        self.domain_name.setObjectName("domain_name")

        self.label_domain_name = QtWidgets.QLabel(parent=self.frame_nmap, text="Range portova (od-do)")
        self.label_domain_name.setGeometry(QtCore.QRect(10,60, 150, 30))
        self.label_domain_name.setObjectName("label_range_portova")

        self.range_porta = QtWidgets.QLineEdit(parent=self.frame_nmap)
        self.range_porta.setGeometry(QtCore.QRect(150, 60, 100, 30))
        self.range_porta.setObjectName("range_porta")


        self.frame_nmap.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
